// Generated by dts-bundle-generator v9.0.0

declare class IconProvider {
	private _eliteMap;
	private _iconMap;
	constructor();
	findElite(flag: number): HTMLImageElement | undefined;
	findIcon(icon: string): HTMLImageElement | undefined;
}
declare const iconProvider: IconProvider;

export {
	iconProvider as IconProvider,
};

export {};
